services:
  biblioreads:
    container_name: biblioreads
    image: docker.io/nesaku/biblioreads:latest
    restart: unless-stopped
    ports:
      - "3000:3000" # Replace with "127.0.0.1:3000:3000" if you are using a reverse proxy
