name: Publish Docker Image

on:
  push:
    branches:
      - "main"

  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: "0 */6 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # arm64 specific
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.2.0
        with:
          platforms: arm64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.6.1
      # arm64 specific

      - name: Check Out Repo
        uses: actions/checkout@v4.1.7

      - name: Login to registry
        uses: docker/login-action@v3.3.0
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6.7.0
        with:
          context: .
          file: docker/Dockerfile
          platforms: linux/amd64,linux/arm64/v8
          push: true
          tags: docker.io/nesaku/biblioreads:latest
